apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xwlkdwpyd-nodejs 
  janus-idp.io/tekton: xwlkdwpyd-nodejs
  backstage.io/kubernetes-id: xwlkdwpyd-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xwlkdwpyd-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml