apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xwlkdwpyd-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:dadb159e303c90da9480ff1e0fdc1c510ad85a2e@sha256:ad24c4daf0dab67378b11751919bdefd93a1e231ea048c6e9be5a2903772abae
          name: container-image
